
services:
  opensearch:
    image: opensearchproject/opensearch:2
    container_name: opensearch
    environment:
      - cluster.name=${OPENSEARCH_CLUSTER_NAME}
      - node.name=${OPENSEARCH_NODE_NAME}
      - discovery.type=${OPENSEARCH_DISCOVERY_TYPE}
      - bootstrap.memory_lock=${OPENSEARCH_BOOTSTRAP_MEMORY_LOCK}
      - "OPENSEARCH_JAVA_OPTS=${OPENSEARCH_JAVA_OPTS}"
      - plugins.security.disabled=${OPENSEARCH_PLUGINS_SECURITY_DISABLED}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "${OPENSEARCH_PORT}:${OPENSEARCH_PORT}"
    networks:
      - logcopilot-net
    restart: unless-stopped

  dashboards:
    image: opensearchproject/opensearch-dashboards:2
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=${OPENSEARCH_HOSTS}
      - OPENSEARCH_SECURITY_ENABLED=${OPENSEARCH_SECURITY_ENABLED}
      - SERVER_HOST=${SERVER_HOST}
    depends_on:
      - opensearch
    ports:
      - "${DASHBOARDS_PORT}:${DASHBOARDS_PORT}"
    networks:
      - logcopilot-net
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: logcopilot-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - logcopilot-net
    restart: unless-stopped

  app:
    build: ./app
    container_name: logcopilot-app
    environment:
      - OPENAI_API_KEY=fake-key
      - OPENAI_BASE_URL=http://192.168.40.214:11434/v1
      - OPENAI_MODEL=gpt-oss          # ou mistral, llama3 etc.
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=logcopilot
      - DB_PASSWORD=logcopilot
      - DB_NAME=logcopilot
      - OPENSEARCH_HOST=http://opensearch:9200
    volumes:
      - ./data/logs:/data/logs
    depends_on:
      - db
      - opensearch
    ports:
      - "8080:8080"
    networks:
      - logcopilot-net
    restart: unless-stopped
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "${N8N_PORT}:${N8N_PORT}"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ${N8N_DATA_DIR}:/home/node/.n8n
    depends_on:
      - app
      - opensearch
    networks:
      - logcopilot-net
    restart: unless-stopped

volumes:
  opensearch-data:
  pgdata:

networks:
  logcopilot-net:
    driver: bridge
